#!/usr/bin/env python3
"""docx 后处理：作者元数据改写＋未引用媒体清理。

两个职责：
1. **stamp_author**：把 docx 作者元数据（dc:creator／cp:lastModifiedBy）改写为
   系统用户（getpass.getuser()）——formatter 产物每次生成/编辑后都必须过一遍。
   源起：python-docx 默认模板写入 "python-docx"；外来模板可能残留原作者信息。
2. **purge_unreferenced_media**：清理 word/media 中未被任何 XML part 引用的图片
   及其关系（模板残留图、增量替换后废弃图），只删"关系＋文件"双侧都无引用的，
   header/footer/footnote 等 part 的引用一并纳入校验，不会误删。

集成：`build_thesis_docx.py` 装配末尾自动 purge＋stamp；
`section_replacer.py` 保存后自动 purge（--no-purge 关）＋stamp（--no-stamp 关）。

用法：
    python3 docx_postprocess.py <file.docx> --check            # 只查看
    python3 docx_postprocess.py <file.docx> --stamp [--user U]
    python3 docx_postprocess.py <file.docx> --purge
    python3 docx_postprocess.py <file.docx> --all [--user U]
"""

from __future__ import annotations

import argparse
import getpass
import re
import zipfile
from datetime import datetime
from pathlib import Path

from docx import Document
from lxml import etree

_RELS_NS = "http://schemas.openxmlformats.org/package/2006/relationships"
# 正文与页眉页脚等可能引用图片的 XML part
_XML_PART_RE = re.compile(
    r"word/(document|header\d*|footer\d*|footnotes|endnotes|comments)\.xml$")
_RID_RE = re.compile(rb'r:(?:embed|id|link)="([^"]+)"')


# ── 作者元数据 ───────────────────────────────────────────────
def check_author(docx_path: str) -> dict:
    cp = Document(docx_path).core_properties
    return {"author": cp.author, "last_modified_by": cp.last_modified_by,
            "comments": cp.comments, "revision": cp.revision}


def stamp_author(docx_path: str, user: str | None = None) -> dict:
    """作者/最后修改者改写为系统用户；清掉 python-docx 默认描述。返回旧值。"""
    user = user or getpass.getuser()
    doc = Document(docx_path)
    cp = doc.core_properties
    old = check_author(docx_path)
    cp.author = user
    cp.last_modified_by = user
    if cp.comments == "generated by python-docx":
        cp.comments = ""
    cp.modified = datetime.now()
    doc.save(docx_path)
    old["stamped_to"] = user
    return old


# ── 未引用媒体清理 ───────────────────────────────────────────
# 可安全垃圾回收的关系类型（其 rId 必然在 XML part 中被显式引用，未被引用即垃圾）；
# styles/settings/numbering/theme/fontTable/customXml/页眉页脚 等隐式关联类型**绝不可动**
_GC_TYPES = ("/image", "/chart", "/oleObject", "/package", "/diagramData",
             "/diagramLayout", "/diagramQuickStyle", "/diagramColors",
             "/video", "/audio", "/chartColorStyle", "/chartStyle",
             "/header", "/footer")
# 隐式关联、永不回收的部件名（basename 精确匹配）
_GC_KEEP_PARTS = {"styles.xml", "settings.xml", "numbering.xml", "fontTable.xml",
                  "webSettings.xml", "theme1.xml"}


def purge_unreferenced_media(docx_path: str) -> dict:
    """垃圾回收：删除未被任何 XML part 引用的图片／图表／嵌入对象等部件，
    级联清理其 .rels 与 Content_Types 覆盖项。返回清理清单。

    判据：document.xml.rels（及其他 .rels）中，Type 属于 _GC_TYPES 且 rId
    未被任何 XML part 引用的关系 → 目标部件及其专有下游部件（colors/style/
    embeddings/themeOverride）一并删除。
    """
    path = Path(docx_path)
    with zipfile.ZipFile(path) as z:
        entries = {i.filename: z.read(i) for i in z.infolist()}

    used_rids: set[str] = set()
    for name, data in entries.items():
        if _XML_PART_RE.match(name):
            used_rids |= {r.decode() for r in _RID_RE.findall(data)}

    # ① 从 document.xml.rels 起收集垃圾部件（目标在包内的相对路径）
    garbage: set[str] = set()          # part 路径，如 word/charts/chart1.xml
    dropped_rels = 0

    def _rels_path_for(part: str) -> str:
        d, b = part.rsplit("/", 1) if "/" in part else ("", part)
        return f"{d}/_rels/{b}.rels" if d else f"_rels/{b}.rels"

    def _sweep_rels(rels_name: str, owner_part: str | None):
        """清一个 .rels：删垃圾关系、登记垃圾部件、级联其 .rels。"""
        nonlocal dropped_rels
        if rels_name not in entries:
            return
        root = etree.fromstring(entries[rels_name])
        base = rels_name.replace("/_rels/", "/")
        base_dir = base.rsplit("/", 1)[0] if "/" in base else ""
        changed = False
        for rel in list(root):
            target = rel.get("Target", "")
            rtype = rel.get("Type", "")
            rid = rel.get("Id", "")
            if not any(rtype.endswith(t) for t in _GC_TYPES):
                continue
            if rid in used_rids:
                continue
            # 外部目标（file:///http）无部件可删，但关系本身是垃圾
            root.remove(rel)
            dropped_rels += 1
            changed = True
            if "://" in target or target.startswith("file:"):
                continue
            import posixpath
            part = target.lstrip("/") if target.startswith("/") else \
                posixpath.normpath(posixpath.join(base_dir, target))
            if part in entries and part.rsplit("/", 1)[-1] not in _GC_KEEP_PARTS:
                garbage.add(part)
        if changed:
            entries[rels_name] = etree.tostring(
                root, xml_declaration=True, encoding="UTF-8", standalone=True)

    _sweep_rels("word/_rels/document.xml.rels", "word/document.xml")

    # ② 级联：垃圾部件自己的 .rels 里的下游部件（colors/style/embeddings/…）
    changed = True
    while changed:
        changed = False
        for part in sorted(garbage):
            rels_name = _rels_path_for(part)
            if rels_name in entries and rels_name not in garbage:
                root = etree.fromstring(entries[rels_name])
                base_dir = part.rsplit("/", 1)[0]
                import posixpath
                for rel in root:
                    target = rel.get("Target", "")
                    if "://" in target or target.startswith("file:"):
                        continue
                    sub = posixpath.normpath(posixpath.join(base_dir, target))
                    if sub in entries and sub not in garbage and \
                            sub.rsplit("/", 1)[-1] not in _GC_KEEP_PARTS:
                        garbage.add(sub)
                        changed = True
                garbage.add(rels_name)

    # ③ 删除垃圾部件与其 .rels，清 Content_Types 覆盖项
    for part in garbage:
        entries.pop(part, None)
    if garbage:
        ct_name = "[Content_Types].xml"
        ct = etree.fromstring(entries[ct_name])
        CT_NS = "http://schemas.openxmlformats.org/package/2006/content-types"
        for ov in list(ct):
            if ov.tag == f"{{{CT_NS}}}Override" and \
                    ov.get("PartName", "").lstrip("/") in garbage:
                ct.remove(ov)
        entries[ct_name] = etree.tostring(
            ct, xml_declaration=True, encoding="UTF-8", standalone=True)

    if dropped_rels or garbage:
        tmp = path.with_suffix(".postproc.tmp")
        with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
            for name, data in entries.items():
                zout.writestr(name, data)
        tmp.replace(path)
    return {"dropped_rels": dropped_rels,
            "dropped_media": sorted(p.rsplit("/", 1)[-1] for p in garbage)}


# ── 版式样式归一（23E 模式产物）──────────────────────────────
# 背景（2026-10-06 用户反馈三问题）：23E 模板（WPS 存盘）的图表题样式不带
# 加粗/居中/字号，Word 重存后 run 级显式格式不可依赖——故全部归一到样式层。
# 图题/表题（规范 3.6(6)(7)：宋体 10.5pt、加粗居中、单倍行距；段前后由样式原值承担）
_CAPTION_STYLE_FIXES = {
    "MBA论文图标题": (True, 10.5, True),
    "MBA表标题": (True, 10.5, True),
}
# 图注/表注（规范 3.6(6)(7)：位于图题下方／表下方，左缩进两汉字符、悬挂两字符
# 〔首行顶格、续行缩两字符左对齐〕、两端对齐、10.5pt、单倍行距、段前段后 0）
_NOTE_STYLE_FIXES = ("MBA论文图表文字", "M论文图表注")


def fix_layout_styles_doc(doc) -> list[str]:
    """fix_layout_styles 的核心（直接作用于 Document 对象，引擎装配时复用）。"""
    from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Pt

    fixes: list[str] = []

    def _set_ea(st):
        rPr = st.element.get_or_add_rPr()
        rFonts = rPr.find(qn("w:rFonts"))
        if rFonts is None:
            rFonts = OxmlElement("w:rFonts")
            rPr.insert(0, rFonts)
        rFonts.set(qn("w:eastAsia"), "宋体")

    for name, (bold, size_pt, center) in _CAPTION_STYLE_FIXES.items():
        try:
            st = doc.styles[name]
        except KeyError:
            continue
        st.font.bold = bold
        st.font.size = Pt(size_pt)
        st.font.name = "Times New Roman"
        _set_ea(st)
        if center:
            st.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        fixes.append(f"样式 {name} 归一（加粗、{size_pt}pt、居中）")

    for name in _NOTE_STYLE_FIXES:
        try:
            st = doc.styles[name]
        except KeyError:
            continue
        st.font.bold = False
        st.font.size = Pt(10.5)
        st.font.name = "Times New Roman"
        _set_ea(st)
        pf = st.paragraph_format
        pf.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY      # 两端对齐
        pf.line_spacing_rule = WD_LINE_SPACING.SINGLE  # 单倍行距
        pf.space_before = Pt(0)
        pf.space_after = Pt(0)
        # 左缩进两字符＋悬挂两字符（首行顶格、续行缩两字符），字符制走 XML；
        # w:ind 在 CT_PPr 中须位于 jc/textDirection/outlineLvl/rPr 之前
        pPr = st.element.get_or_add_pPr()
        ind = pPr.find(qn("w:ind"))
        if ind is not None:
            pPr.remove(ind)
        ind = OxmlElement("w:ind")
        ind.set(qn("w:leftChars"), "200")
        ind.set(qn("w:hangingChars"), "200")
        anchor = None
        for tag in ("w:contextualSpacing", "w:mirrorIndents", "w:suppressOverlap",
                    "w:jc", "w:textDirection", "w:textAlignment",
                    "w:textboxTightWrap", "w:outlineLvl", "w:divId",
                    "w:cnfStyle", "w:rPr", "w:sectPr", "w:pPrChange"):
            anchor = pPr.find(qn(tag))
            if anchor is not None:
                break
        if anchor is not None:
            anchor.addprevious(ind)
        else:
            pPr.append(ind)
        fixes.append(f"样式 {name} 归一（10.5pt、两端对齐、左缩进2字符＋悬挂2字符、单倍行距、段前后0）")

    try:
        ref = doc.styles["MBA论文参考文献"]
        pPr = ref.element.find(qn("w:pPr"))
        numPr = pPr.find(qn("w:numPr")) if pPr is not None else None
        if numPr is not None:
            pPr.remove(numPr)
            fixes.append("参考文献样式去除自动编号（numPr）")
    except KeyError:
        pass

    # 表格样式去底色（2026-10-06 用户裁定：第一行不要绿底；样式基线＝全表无底色）：
    # 模板「MBA论文表格」firstRow 带绿底 008000、band1Horz 带白底——全部剥除；
    # 与绿底配套的首行白字（color=FFFFFF）一并去除，保留加粗；
    # basedOn 断链到 Normal Table——否则 Word 存盘时会从父样式（Table List 2 等
    # WPS 内置绿底表样式）重新物化出底纹（2026-10-06 实证：修复被 Word 重存覆盖）
    try:
        tst = doc.styles["MBA论文表格"]
        removed = 0
        scopes = tst.element.findall(qn("w:tblStylePr")) + \
            ([tst.element.find(qn("w:tblPr"))] if tst.element.find(qn("w:tblPr")) is not None else [])
        for scope in scopes:
            for shd in scope.findall(f".//{qn('w:shd')}"):
                shd.getparent().remove(shd)
                removed += 1
            for color in scope.findall(f".//{qn('w:color')}"):
                if color.get(qn("w:val")) == "FFFFFF":
                    color.getparent().remove(color)
                    removed += 1
        normal_tbl_id = next((s.style_id for s in doc.styles
                              if s.name == "Normal Table"), None)
        bo = tst.element.find(qn("w:basedOn"))
        if bo is not None and normal_tbl_id and bo.get(qn("w:val")) != normal_tbl_id:
            bo.set(qn("w:val"), normal_tbl_id)
            removed += 1
        if removed:
            fixes.append(f"表格样式去底色 ×{removed}（首行绿底/白字清除＋basedOn 断链 Normal Table）")
    except KeyError:
        pass

    # 附录小节标题去大纲（2026-10-06 裁定：A.1/B.1/C.1 等不进目录）：
    # 确保「MBA论文附录节标题」克隆样式存在，把一级节标题样式的 A.1 式段落换过去
    import copy as _copy
    import re as _re
    style_names = {s.name for s in doc.styles}
    if "MBA论文附录节标题" not in style_names and "MBA论文一级节标题" in style_names:
        src = doc.styles["MBA论文一级节标题"]
        new_el = _copy.deepcopy(src.element)
        new_el.set(qn("w:styleId"), "MBAAppendixH1")
        new_el.find(qn("w:name")).set(qn("w:val"), "MBA论文附录节标题")
        _pPr = new_el.find(qn("w:pPr"))
        if _pPr is not None:
            _ol = _pPr.find(qn("w:outlineLvl"))
            if _ol is not None:
                _pPr.remove(_ol)
        doc.styles.element.append(new_el)
    if "MBA论文附录节标题" in {s.name for s in doc.styles}:
        n_app = 0
        for para in doc.paragraphs:
            if para.style and para.style.name == "MBA论文一级节标题" and \
                    _re.match(r"^[A-Z]\.\d+\s", para.text.strip()):
                para.style = doc.styles["MBA论文附录节标题"]
                n_app += 1
        if n_app:
            fixes.append(f"附录小节标题去大纲 ×{n_app}（目录须 F9 刷新后剔除旧条目）")

    # 页眉下边框：pBdr 在 CT_PPr 中位于 shd/tabs/spacing/ind/jc 之前
    bordered = 0
    for sec in doc.sections:
        if sec.header.is_linked_to_previous:
            continue
        for para in sec.header.paragraphs:
            pPr = para._p.get_or_add_pPr()
            if pPr.find(qn("w:pBdr")) is not None:
                continue
            pBdr = OxmlElement("w:pBdr")
            bottom = OxmlElement("w:bottom")
            bottom.set(qn("w:val"), "single")
            bottom.set(qn("w:sz"), "6")      # 0.75pt
            bottom.set(qn("w:space"), "1")
            bottom.set(qn("w:color"), "000000")
            pBdr.append(bottom)
            anchor = None
            for tag in ("w:shd", "w:tabs", "w:spacing", "w:ind", "w:jc",
                        "w:rPr", "w:sectPr"):
                anchor = pPr.find(qn(tag))
                if anchor is not None:
                    break
            if anchor is not None:
                anchor.addprevious(pBdr)
            else:
                pPr.append(pBdr)
            bordered += 1
    if bordered:
        fixes.append(f"页眉下边框 ×{bordered} 段")
    return fixes


def fix_layout_styles(docx_path: str) -> list[str]:
    """版式归一（作用在样式层，不动正文内容）：见 fix_layout_styles_doc。"""
    from docx import Document
    doc = Document(docx_path)
    fixes = fix_layout_styles_doc(doc)
    doc.save(docx_path)
    return fixes


# ── 编号与标题间分隔：半角空格 → 全角空格 ─────────────────────
# （2026-10-06 用户裁定；md 源文件保持半角不动，转换只发生在渲染层与本修复层）
_SEP_TARGET_STYLES = {"MBA论文章标题", "MBA论文一级节标题", "MBA论文二级节标题",
                      "MBA论文三级节标题", "MBA论文附录节标题",
                      "MBA论文图标题", "MBA表标题"}


def fix_number_separators_doc(doc) -> list[str]:
    """章号/节号/表号/图号与标题之间的半角空格 → 全角空格（U+3000）。

    作用于标题/题注样式段落与各节页眉；目录域条目不动（F9 刷新后自动跟随）。
    附表题的双色结构（题号粗体＋「（请…）」说明常规）按"（请"断点保留。
    """
    from thesis23e_engine import _fullwidth_sep

    def _rewrite(para) -> bool:
        text = para.text
        new = _fullwidth_sep(text)
        if new == text or not para.runs:
            return False
        runs = para.runs
        split_at = new.find("（请")
        if split_at > 0 and len(runs) >= 2:      # 附表题双色保持
            runs[0].text = new[:split_at]
            runs[1].text = new[split_at:]
            for r in runs[2:]:
                r.text = ""
        else:
            runs[0].text = new
            for r in runs[1:]:
                r.text = ""
        return True

    n_para = 0
    for para in doc.paragraphs:
        if para.style and para.style.name in _SEP_TARGET_STYLES and _rewrite(para):
            n_para += 1
    n_hdr = 0
    for sec in doc.sections:
        if sec.header.is_linked_to_previous:
            continue
        for para in sec.header.paragraphs:
            if _rewrite(para):
                n_hdr += 1
    fixes = []
    if n_para:
        fixes.append(f"编号-标题分隔全角化：标题/题注段落 ×{n_para}")
    if n_hdr:
        fixes.append(f"编号-标题分隔全角化：页眉 ×{n_hdr}")
    return fixes


def fix_number_separators(docx_path: str) -> list[str]:
    from docx import Document
    doc = Document(docx_path)
    fixes = fix_number_separators_doc(doc)
    doc.save(docx_path)
    return fixes


def main():
    ap = argparse.ArgumentParser(description="docx 后处理：作者改写＋残留媒体清理＋版式归一")
    ap.add_argument("docx")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="只打印当前元数据与残留媒体")
    g.add_argument("--stamp", action="store_true", help="作者改写为系统用户")
    g.add_argument("--purge", action="store_true", help="清理未引用媒体")
    g.add_argument("--fix-styles", action="store_true",
                   help="版式归一：图表题/注样式＋文献去自动编号＋页眉下边框（自动备份）")
    g.add_argument("--fix-seps", action="store_true",
                   help="编号-标题间半角空格改全角（标题/题注/页眉；自动备份）")
    g.add_argument("--all", action="store_true", help="purge＋stamp")
    ap.add_argument("--user", default=None, help="指定用户名（默认取系统用户）")
    args = ap.parse_args()

    if args.check:
        print(check_author(args.docx))
        with zipfile.ZipFile(args.docx) as z:
            media = [n for n in z.namelist() if n.startswith("word/media/")]
            used = set()
            for n in z.namelist():
                if _XML_PART_RE.match(n):
                    used |= {r.decode() for r in _RID_RE.findall(z.read(n))}
            for n in media:
                print(f"  {n}")
        return
    if args.purge or args.all:
        info = purge_unreferenced_media(args.docx)
        print(f"purge: 删关系 {info['dropped_rels']} 项，删文件 {info['dropped_media']}")
    if args.stamp or args.all:
        old = stamp_author(args.docx, args.user)
        print(f"stamp: {old['author']!r}/{old['last_modified_by']!r} → {old['stamped_to']!r}")
    if args.fix_styles:
        from section_replacer import backup
        print(f"备份 → {backup(args.docx)}")
        for f in fix_layout_styles(args.docx):
            print(f"  {f}")
    if args.fix_seps:
        from section_replacer import backup
        print(f"备份 → {backup(args.docx)}")
        for f in fix_number_separators(args.docx):
            print(f"  {f}")


if __name__ == "__main__":
    main()
